#!/usr/bin/python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# A class for color-constants
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pygame-fbgui
#
# ----------------------------------------------------------------------------

import pygame

class Color(object):
  """ Color constants """

  TRANSPARENT          = pygame.Color(0,0,0,0)

  # standard color-names
  ALICEBLUE            = pygame.Color("#F0F8FF")
  ANTIQUEWHITE         = pygame.Color("#FAEBD7")
  AQUA                 = pygame.Color("#00FFFF")
  AQUAMARINE           = pygame.Color("#7FFFD4")
  AZURE                = pygame.Color("#F0FFFF")
  BEIGE                = pygame.Color("#F5F5DC")
  BISQUE               = pygame.Color("#FFE4C4")
  BLACK                = pygame.Color("#000000")
  BLANCHEDALMOND       = pygame.Color("#FFEBCD")
  BLUE                 = pygame.Color("#0000FF")
  BLUEVIOLET           = pygame.Color("#8A2BE2")
  BROWN                = pygame.Color("#A52A2A")
  BURLYWOOD            = pygame.Color("#DEB887")
  CADETBLUE            = pygame.Color("#5F9EA0")
  CHARTREUSE           = pygame.Color("#7FFF00")
  CHOCOLATE            = pygame.Color("#D2691E")
  CORAL                = pygame.Color("#FF7F50")
  CORNFLOWERBLUE       = pygame.Color("#6495ED")
  CORNSILK             = pygame.Color("#FFF8DC")
  CRIMSON              = pygame.Color("#DC143C")
  CYAN                 = pygame.Color("#00FFFF")
  DARKBLUE             = pygame.Color("#00008B")
  DARKCYAN             = pygame.Color("#008B8B")
  DARKGOLDENROD        = pygame.Color("#B8860B")
  DARKGRAY             = pygame.Color("#A9A9A9")
  DARKGREY             = pygame.Color("#A9A9A9")
  DARKGREEN            = pygame.Color("#006400")
  DARKKHAKI            = pygame.Color("#BDB76B")
  DARKMAGENTA          = pygame.Color("#8B008B")
  DARKOLIVEGREEN       = pygame.Color("#556B2F")
  DARKORANGE           = pygame.Color("#FF8C00")
  DARKORCHID           = pygame.Color("#9932CC")
  DARKRED              = pygame.Color("#8B0000")
  DARKSALMON           = pygame.Color("#E9967A")
  DARKSEAGREEN         = pygame.Color("#8FBC8F")
  DARKSLATEBLUE        = pygame.Color("#483D8B")
  DARKSLATEGRAY        = pygame.Color("#2F4F4F")
  DARKSLATEGREY        = pygame.Color("#2F4F4F")
  DARKTURQUOISE        = pygame.Color("#00CED1")
  DARKVIOLET           = pygame.Color("#9400D3")
  DEEPPINK             = pygame.Color("#FF1493")
  DEEPSKYBLUE          = pygame.Color("#00BFFF")
  DIMGRAY              = pygame.Color("#696969")
  DIMGREY              = pygame.Color("#696969")
  DODGERBLUE           = pygame.Color("#1E90FF")
  FIREBRICK            = pygame.Color("#B22222")
  FLORALWHITE          = pygame.Color("#FFFAF0")
  FORESTGREEN          = pygame.Color("#228B22")
  FUCHSIA              = pygame.Color("#FF00FF")
  GAINSBORO            = pygame.Color("#DCDCDC")
  GHOSTWHITE           = pygame.Color("#F8F8FF")
  GOLD                 = pygame.Color("#FFD700")
  GOLDENROD            = pygame.Color("#DAA520")
  GRAY                 = pygame.Color("#808080")
  GREY                 = pygame.Color("#808080")
  GREEN                = pygame.Color("#008000")
  GREENYELLOW          = pygame.Color("#ADFF2F")
  HONEYDEW             = pygame.Color("#F0FFF0")
  HOTPINK              = pygame.Color("#FF69B4")
  INDIANRED            = pygame.Color("#CD5C5C")
  INDIGO               = pygame.Color("#4B0082")
  IVORY                = pygame.Color("#FFFFF0")
  KHAKI                = pygame.Color("#F0E68C")
  LAVENDER             = pygame.Color("#E6E6FA")
  LAVENDERBLUSH        = pygame.Color("#FFF0F5")
  LAWNGREEN            = pygame.Color("#7CFC00")
  LEMONCHIFFON         = pygame.Color("#FFFACD")
  LIGHTBLUE            = pygame.Color("#ADD8E6")
  LIGHTCORAL           = pygame.Color("#F08080")
  LIGHTCYAN            = pygame.Color("#E0FFFF")
  LIGHTGOLDENRODYELLOW = pygame.Color("#FAFAD2")
  LIGHTGRAY            = pygame.Color("#D3D3D3")
  LIGHTGREY            = pygame.Color("#D3D3D3")
  LIGHTGREEN           = pygame.Color("#90EE90")
  LIGHTPINK            = pygame.Color("#FFB6C1")
  LIGHTSALMON          = pygame.Color("#FFA07A")
  LIGHTSEAGREEN        = pygame.Color("#20B2AA")
  LIGHTSKYBLUE         = pygame.Color("#87CEFA")
  LIGHTSLATEGRAY       = pygame.Color("#778899")
  LIGHTSLATEGREY       = pygame.Color("#778899")
  LIGHTSTEELBLUE       = pygame.Color("#B0C4DE")
  LIGHTYELLOW          = pygame.Color("#FFFFE0")
  LIME                 = pygame.Color("#00FF00")
  LIMEGREEN            = pygame.Color("#32CD32")
  LINEN                = pygame.Color("#FAF0E6")
  MAGENTA              = pygame.Color("#FF00FF")
  MAROON               = pygame.Color("#800000")
  MEDIUMAQUAMARINE     = pygame.Color("#66CDAA")
  MEDIUMBLUE           = pygame.Color("#0000CD")
  MEDIUMORCHID         = pygame.Color("#BA55D3")
  MEDIUMPURPLE         = pygame.Color("#9370DB")
  MEDIUMSEAGREEN       = pygame.Color("#3CB371")
  MEDIUMSLATEBLUE      = pygame.Color("#7B68EE")
  MEDIUMSPRINGGREEN    = pygame.Color("#00FA9A")
  MEDIUMTURQUOISE      = pygame.Color("#48D1CC")
  MEDIUMVIOLETRED      = pygame.Color("#C71585")
  MIDNIGHTBLUE         = pygame.Color("#191970")
  MINTCREAM            = pygame.Color("#F5FFFA")
  MISTYROSE            = pygame.Color("#FFE4E1")
  MOCCASIN             = pygame.Color("#FFE4B5")
  NAVAJOWHITE          = pygame.Color("#FFDEAD")
  NAVY                 = pygame.Color("#000080")
  OLDLACE              = pygame.Color("#FDF5E6")
  OLIVE                = pygame.Color("#808000")
  OLIVEDRAB            = pygame.Color("#6B8E23")
  ORANGE               = pygame.Color("#FFA500")
  ORANGERED            = pygame.Color("#FF4500")
  ORCHID               = pygame.Color("#DA70D6")
  PALEGOLDENROD        = pygame.Color("#EEE8AA")
  PALEGREEN            = pygame.Color("#98FB98")
  PALETURQUOISE        = pygame.Color("#AFEEEE")
  PALEVIOLETRED        = pygame.Color("#DB7093")
  PAPAYAWHIP           = pygame.Color("#FFEFD5")
  PEACHPUFF            = pygame.Color("#FFDAB9")
  PERU                 = pygame.Color("#CD853F")
  PINK                 = pygame.Color("#FFC0CB")
  PLUM                 = pygame.Color("#DDA0DD")
  POWDERBLUE           = pygame.Color("#B0E0E6")
  PURPLE               = pygame.Color("#800080")
  REBECCAPURPLE        = pygame.Color("#663399")
  RED                  = pygame.Color("#FF0000")
  ROSYBROWN            = pygame.Color("#BC8F8F")
  ROYALBLUE            = pygame.Color("#4169E1")
  SADDLEBROWN          = pygame.Color("#8B4513")
  SALMON               = pygame.Color("#FA8072")
  SANDYBROWN           = pygame.Color("#F4A460")
  SEAGREEN             = pygame.Color("#2E8B57")
  SEASHELL             = pygame.Color("#FFF5EE")
  SIENNA               = pygame.Color("#A0522D")
  SILVER               = pygame.Color("#C0C0C0")
  SKYBLUE              = pygame.Color("#87CEEB")
  SLATEBLUE            = pygame.Color("#6A5ACD")
  SLATEGRAY            = pygame.Color("#708090")
  SLATEGREY            = pygame.Color("#708090")
  SNOW                 = pygame.Color("#FFFAFA")
  SPRINGGREEN          = pygame.Color("#00FF7F")
  STEELBLUE            = pygame.Color("#4682B4")
  TAN                  = pygame.Color("#D2B48C")
  TEAL                 = pygame.Color("#008080")
  THISTLE              = pygame.Color("#D8BFD8")
  TOMATO               = pygame.Color("#FF6347")
  TURQUOISE            = pygame.Color("#40E0D0")
  VIOLET               = pygame.Color("#EE82EE")
  WHEAT                = pygame.Color("#F5DEB3")
  WHITE                = pygame.Color("#FFFFFF")
  WHITESMOKE           = pygame.Color("#F5F5F5")
  YELLOW               = pygame.Color("#FFFF00")
  YELLOWGREEN          = pygame.Color("#9ACD32")

  # shades (selected pure colors)
  GRAY100 = pygame.Color("#ffffff")
  GRAY095 = pygame.Color("#f2f2f2")
  GRAY090 = pygame.Color("#e6e6e6")
  GRAY085 = pygame.Color("#d9d9d9")
  GRAY080 = pygame.Color("#cccccc")
  GRAY075 = pygame.Color("#bfbfbf")
  GRAY070 = pygame.Color("#b3b3b3")
  GRAY065 = pygame.Color("#a6a6a6")
  GRAY060 = pygame.Color("#999999")
  GRAY055 = pygame.Color("#8c8c8c")
  GRAY050 = pygame.Color("#808080")
  GRAY045 = pygame.Color("#737373")
  GRAY040 = pygame.Color("#666666")
  GRAY035 = pygame.Color("#595959")
  GRAY030 = pygame.Color("#4d4d4d")
  GRAY025 = pygame.Color("#404040")
  GRAY020 = pygame.Color("#333333")
  GRAY015 = pygame.Color("#262626")
  GRAY010 = pygame.Color("#1a1a1a")
  GRAY005 = pygame.Color("#0d0d0d")
  GRAY000 = pygame.Color("#000000")

  RED100 = pygame.Color("#ffffff")
  RED095 = pygame.Color("#ffe6e6")
  RED090 = pygame.Color("#ffcccc")
  RED085 = pygame.Color("#ffb3b3")
  RED080 = pygame.Color("#ff9999")
  RED075 = pygame.Color("#ff8080")
  RED070 = pygame.Color("#ff6666")
  RED065 = pygame.Color("#ff4d4d")
  RED060 = pygame.Color("#ff3333")
  RED055 = pygame.Color("#ff1a1a")
  RED050 = pygame.Color("#ff0000")
  RED045 = pygame.Color("#e60000")
  RED040 = pygame.Color("#cc0000")
  RED035 = pygame.Color("#b30000")
  RED030 = pygame.Color("#990000")
  RED025 = pygame.Color("#800000")
  RED020 = pygame.Color("#660000")
  RED015 = pygame.Color("#4d0000")
  RED010 = pygame.Color("#330000")
  RED005 = pygame.Color("#1a0000")
  RED000 = pygame.Color("#000000")

  GREEN100 = pygame.Color("#ffffff")
  GREEN095 = pygame.Color("#e6ffe6")
  GREEN090 = pygame.Color("#ccffcc")
  GREEN085 = pygame.Color("#b3ffb3")
  GREEN080 = pygame.Color("#99ff99")
  GREEN075 = pygame.Color("#80ff80")
  GREEN070 = pygame.Color("#66ff66")
  GREEN065 = pygame.Color("#4dff4d")
  GREEN060 = pygame.Color("#33ff33")
  GREEN055 = pygame.Color("#1aff1a")
  GREEN050 = pygame.Color("#00ff00")
  GREEN045 = pygame.Color("#00e600")
  GREEN040 = pygame.Color("#00cc00")
  GREEN035 = pygame.Color("#00b300")
  GREEN030 = pygame.Color("#009900")
  GREEN025 = pygame.Color("#008000")
  GREEN020 = pygame.Color("#006600")
  GREEN015 = pygame.Color("#004d00")
  GREEN010 = pygame.Color("#003300")
  GREEN005 = pygame.Color("#001a00")
  GREEN000 = pygame.Color("#000000")

  BLUE100 = pygame.Color("#ffffff")
  BLUE095 = pygame.Color("#e6e6ff")
  BLUE090 = pygame.Color("#ccccff")
  BLUE085 = pygame.Color("#b3b3ff")
  BLUE080 = pygame.Color("#9999ff")
  BLUE075 = pygame.Color("#8080ff")
  BLUE070 = pygame.Color("#6666ff")
  BLUE065 = pygame.Color("#4d4dff")
  BLUE060 = pygame.Color("#3333ff")
  BLUE055 = pygame.Color("#1a1aff")
  BLUE050 = pygame.Color("#0000ff")
  BLUE045 = pygame.Color("#0000e6")
  BLUE040 = pygame.Color("#0000cc")
  BLUE035 = pygame.Color("#0000b3")
  BLUE030 = pygame.Color("#000099")
  BLUE025 = pygame.Color("#000080")
  BLUE020 = pygame.Color("#000066")
  BLUE015 = pygame.Color("#00004d")
  BLUE010 = pygame.Color("#000033")
  BLUE005 = pygame.Color("#00001a")
  BLUE000 = pygame.Color("#000000")

  # --- compare two colors   -------------------------------------------------

  @staticmethod
  def eq(color1,color2):
    """ compare two colors """

    return (color1.r == color2.r and
            color1.g == color2.g and
            color1.b == color2.b and
            color1.a == color2.a)

  # --- return a lighter version of a color   --------------------------------

  @staticmethod
  def lighten(color):
    """ return a lighter version of a color """

    return pygame.Color(min(255,int(1.1*color.r)),
                        min(255,int(1.1*color.g)),
                        min(255,int(1.1*color.b)),
                        color.a)

  # --- return a darker version of a color   --------------------------------

  @staticmethod
  def darken(color):
    """ return a darker version of a color """

    return pygame.Color(int(0.9*color.r),
                        int(0.9*color.g),
                        int(0.9*color.b),
                        color.a)
