#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pygame-fbgui
#
# --------------------------------------------------------------------------

PACKAGES="python3-pygame"
PROJECT="pygame-fbgui"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

get_new_packages() {
  local p packages
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    if dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok"; then
      echo "ok" >&2
    else
      echo "not installed" >&2
      packages+=" $p"
    fi
  done
  echo "$packages"
}

install_packages() {
  new_packages=$(get_new_packages $PACKAGES)
  if [ -n "$new_packages" ]; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y --no-upgrade install $new_packages
  fi
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
    target="${f#*files}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done
}

# --- configure system   ----------------------------------------------------

configure_system() {
  #get python3-version (major.minor)
  py_ver=$(python3 -V)
  py_ver="${py_ver#* }"
  py_ver="${py_ver%.*}"

  # add directory to python-path
  if ! grep -q "/usr/local/lib/python%d.%d/site-packages" \
                                 /etc/python$py_ver/sitecustomize.py; then
    echo -e "[INFO] updating /etc/python$py_ver/sitecustomize.py"
    cat >> /etc/python$py_ver/sitecustomize.py <<EOF
import site
import sys
site.addsitedir('/usr/local/lib/python%d.%d/site-packages' %
                            (sys.version_info[0],sys.version_info[1]))
EOF
  fi
}

# --- main program   --------------------------------------------------------

install_packages

install_files
configure_system

echo "[INFO] installation completed"
